### ISSUE TITLE
Scrolling inside the source view causes panic

### ISSUE THREAD

**Issue by object88** [HeySquirrel/tribe#14]
With focus on the Source (F1), use a MacBook Pro trackpad to scroll through the code.  (Unknown if reproducible on other systems.)  It appears that for every line that the scroll action passes through, a requests are made to populate other panels.  If the user scrolls vigorously, the app will panic:

```
│                                                                              │└──────────────────────────────────────────────────────────────────────────────┘
│                                                                              │┌─Contributors: add-new-items.spec.js Lines 105-107 ───────────────────────────┐
└──────────────────────────────────────────────────────────────────────────────┘│  Lovisa Svallingson   - 1 Commits - 6 months ago                             │
┌─Contributors: add-new-items.spec.js ─────────────────────────────────────────┐│                                                                              │
│  ender2012            - 1 Commits - 3 months ago                             ││                                                                              │
│  David Adams          - 1 Commits - 3 months ago                             ││                                                                              │
│  Michael Filbin       - 1 Commits - 4 months ago                             ││                                                 2017/09/28 12:15:57 exit status 128vid Vong           - 1 Commits - 4 months ago                             ││                                                                              │
2017/09/28 12:15:57 Loader panics: exit status 128                             ││                                                                              │
│  Kaitlin Barrer       - 2 Commits - 5 months ago                             ││                                                                              │
panic: Loader panics: exit status 128 6 months ago                             ││                                                                              │
│                                                                              ││                                                                              │
│                                                                              ││                                                                              │
│                                                                              ││                                                                              │
goroutine 6 [running]:                                                         ││                                                                              │
log.Panicln(0xc420a6dfb8, 0x1, 0x1)────────────────────────────────────────────┘└──────────────────────────────────────────────────────────────────────────────┘
	/usr/local/Cellar/go/1.9/libexec/src/log/log.go:344 +0xc0
github.com/HeySquirrel/tribe/blame/model.(*cache).startCacheWorkers.func1(0xc42017a570)
	/Users/bropa18/work/src/github.com/HeySquirrel/tribe/blame/model/annotate.go:121 +0xe6
created by github.com/HeySquirrel/tribe/blame/model.(*cache).startCacheWorkers
	/Users/bropa18/work/src/github.com/HeySquirrel/tribe/blame/model/annotate.go:117 +0x48
```

**Comment by aesterline** [comment]
@object88 I think I fixed this. Can you pull the latest source and give it a try?

**Comment by object88** [comment]
I would love to!  Will check it out today and get back to you.

**Comment by object88** [comment]
@aesterline , I pulled from master & rebuilt the project.  I no longer see any panic with scrolling through the source view.  Nice work!
