### ISSUE TITLE
Reaching down the file crashes the tribe, leaving the color set in the shell transparent

### ISSUE THREAD

**Issue by porcevader** [HeySquirrel/tribe#20]
Title is all.
I will try to reproduce and nail down the condition.

**Comment by porcevader** [comment]
The crash is reliably reproduced by issuing tribe blame toward the end of the file.
For instance, I have file whose line length is 321.

$ tribe blame -L320 myfile.go

..
017/11/21 18:59:31 Loader panics: exit status 128
panic: Loader panics: exit status 128
goroutine 6 [running]:
log.Panicln(0xc42024cfb8, 0x1, 0x1)
/usr/lib/...golang/src/log/log.go:344 +0xc0                                                     
github.com/HeySquirrel/tribe/blame/model.(*cache).startCacheWorkers.func1(0xc4201b00c0)                       /usr/local/.../src/github.com/HeySquirrel/tribe/blame/model/annotate.go:126 +0xe6
created by github.com/HeySquirrel/tribe/blame/model.(*cache).startCacheWorkers
/usr/local/.../src/github.com/HeySquirrel/tribe/blame/model/annotate.go:122 +0x48
